### ISSUE TITLE
Feature request: Template and link to device

### ISSUE THREAD

**Issue by kgn3400** [gjohansson-ST/attribute_as_sensor#10]
**Describe the bug**

Hallå där  😄

Well i know we have the builtin template helper. But it would be nice feature if your attribute to sensor helper supported a template to get the correct content of the tracked attribute.

And of course, the new link to device feature in Home assistant 2024.7 🤓

Best regards
Kurt G. Nielsen

**Version**
Which version are you running.

**Expected behavior**

**Additional context**

**Comment by gjohansson-ST** [comment]
Can you expand what you mean by using a template?
You mean adding a `value_template` field to be able to expand and mod the resulting value or using a template for the entity and/or attribute?

**Comment by kgn3400** [comment]
Yes, a value template would be a nice optional  enhancement to could use on the choosen state attribute.

Best Regards
Kurt G. Nielsen
