### ISSUE TITLE
Missing icon image for Attribute as sensor helper

### ISSUE THREAD

**Issue by kgn3400** [gjohansson-ST/attribute_as_sensor#5]
**Describe the bug**
When adding a new helper, the icon for the Attribute as sensor is missing and image for icon not available are displayed instead.

You only have uploaded a logo.png. Shouldn't there at least have been an icon.png?

The documentation states:
If a domain is missing the icon.png file, 404 will be served
If a domain is missing the logo.png file, the icon.png is served instead (if available).
If a domain is missing the icon@2x.png file, the icon.png is served instead (if available).
If a domain is missing the logo@2x.png file:
the icon@2x.png is served if available and logo.png is missing
the logo.png is served instead (if available).
If a image optimised for dark themes (image is prefixed with 'dark_') is missing, it's non-prefixed match will be served instead (if available).

Ps. Awesome helper, simple and useful :-)

Best regards
Kurt G. Nielsen

**Version**
1.1

**Expected behavior**
The image from logo.png as a icon.png.

**Additional context**
If you don't have the time, I can copy and create a pr with a new icon.png for this issue.

**Comment by gjohansson-ST** [comment]
https://github.com/home-assistant/brands/pull/5611
Thanks for pointing it out

**Comment by gjohansson-ST** [comment]
Icon has been added so closing this. Thanks 👍
